### PR TITLE
fix: Solve 'conflicting contents for sourcemap' rollup issue

### PR DESCRIPTION
**Pull request by sandrina-p**
Solves #618.

After a quick search, it seems the problem is on `rollup-plugin-vue` that was reported on version 4.7.0.

A couple of months ago we updated most of our dependencies, including `rollup-plugin-vue` to v5.0.0. https://github.com/okTurtles/group-income-simple/pull/574

The [only fix I've found](https://github.com/vuejs/rollup-plugin-vue/issues/238) is to rollback it back to 4.2.0. Based on their release history, it seems they added a feature related to sourcemaps at [v4.3.0](https://github.com/vuejs/rollup-plugin-vue/releases/tag/v4.3.0) which might be the root of the problem.

I've tried to change several files around the project and didn't have the issue anymore :tada:

### CODE REVIEW

**Comment by taoeffect** [comment]
I'm not entirely sure if this is the real fix that we're looking for, since in downgrading to 4.2.0 we would be missing out on a bunch of [important bugfixes](https://github.com/vuejs/rollup-plugin-vue/blob/master/CHANGELOG.md)... Ideally a fix would come in the form of a fork + PR to their project, really fixing the issue.

It's difficult for me to review this also, because I would need to go through and evaluate the costs of giving up all of the bug fixes, as well as the downgraded Vue compiler. Also, I have a vague memory of having to upgrade `rollup-plugin-vue` in order to fix some other problem, so downgrading could potentially re-introduce whatever that was. So while this might solve #618, I do not consider this a real fix. 😕

**Review by taoeffect — CHANGES_REQUESTED** [review]
I'm afraid I can't accept a fix that downgrades the vue compiler and re-introduces known bugs.

**Comment by sandrina-p** [comment]
I also explored more the tools behind this https://github.com/okTurtles/group-income-simple/pull/583 and couldn't find a working solution.

I saw the history and I didn't saw any bug fix as important as the ability to have an efficient hot-reload system with source maps working. This is one of the dev features I use the most when developing and if it doesn't work properly it's really annoying :/

**Comment by taoeffect** [comment]
> I didn't saw any bug fix as important as the ability to have an efficient hot-reload system with source maps working. 

Well, AFAIK it sounds like downgrading to 4.2.0 doesn't fix the sourcemaps? So if you don't want to dive into the details of how the rollup plugin works, you can disable sourcemaps if it really annoys you per the Troubleshooting docs.

**Comment by taoeffect** [comment]
For now, closing this in favor of the `DISABLE_SOURCEMAPS` environment variable introduced in #611.

**Comment by sandrina-p** [comment]
> Well, AFAIK it sounds like downgrading to 4.2.0 doesn't fix the sourcemaps?

Yes it does, I tested it

**Comment by taoeffect** [comment]
> Yes it does, I tested it

AFAICT from their release notes, 4.2.0 doesn't support sourcemaps, so it's the same as disabling them. Sourcemaps were introduced in [4.3.0](https://github.com/vuejs/rollup-plugin-vue/releases/tag/v4.3.0).

**Comment by sandrina-p** [comment]
Okay, so something else is generating the sourcemaps because I just tried it again and it works:

This branch (v4.2.0)
image

Master (v5.1.0)
image

And I checked the versions installed directly at `node_modules` folder to make sure I didn't have any cache problems on that package.

**Comment by taoeffect** [comment]
Hmm. OK. Well then. I'm not sure what's going on, not an expert on sourcemaps. But maybe someone who is will fix these issues! 😄

**Comment by sandrina-p** [comment]
So... can we downgrade to 4.2.0 for now since I find it more important than all the other minor bug fixes? Unless there's something really critical fixed on 5.x. But so far you didn't point anything, so that's why I think it's worth the trade-off.

**Comment by taoeffect** [comment]
The [major update to the compiler](https://github.com/vuejs/rollup-plugin-vue/commit/e215fe7#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R48-R49) seems like something we need, I don't consider it a worthwhile tradeoff to be using an outdated Vue.js compiler...

**Comment by sandrina-p** [comment]
Okay then, let's keep it as it is. In the future, I'll try again to fix this evil issue

**Pull request closed without merging**
