### PR TITLE
#362 - Uniform way of target elements on FE tests

### LINKED ISSUE #362: Uniform way of targeting elements during tests.
### Problem

Following my comment on this PR #355 
```diff
-   .wait(() => document.querySelectorAll('.member').length > 0)
+   .wait(() => document.querySelectorAll('.invitee').length > 0)
```
> May I ask if we have any "strategy" to target elements used by integration tests?
>
> By only seeing this PR, I can see we are using any kind of way to target an element (id, class, attr, etc..) without consistency. That might cause some confusion during code development. For instance, when I use classes, I expect to use them as a way to style the layout, not to be used as a test target. 

### Solution

> My suggestion here, would be to find a way to improve this lack of consistency. Example: Add an attr`data-test` to elements used to run tests. I see some advantages with that:
> - During developing an element with that attribute is easily "marked" as an element used for tests.
> - Any other element's property (class, id, attr) can be changed without worrying too much about breaking the test but at the same time keeping in mind that element is used for tests.
> - These kind of changes (like this PR) can be avoid. 

And @taoeffect answer

> Yes, that sounds like a great plan! 👍  Feel free to do that, and along the way check with @hubudibu about cleaning up and removing an no-longer-used IDs or classes.

---

So, @hubudibu what do you think about it and where do you believe it's a good starting point? Also defining a naming convention is important as well. I don't have preferences, but personally i like camelCase 🙊

### PR DESCRIPTION
**Pull request by sandrina-p**
Following #362 I've refactored all elements targeted by `id`, `class` or  any other attribute to a single way of targeting: `data-test` attribute.

I've created a utility function to avoid repeating `'[data-test="x"]'` everytime.

```js
// Access any element by its data-test attribute
function elT (el) {
  return `[data-test=${el}]`
}
```

Example of the refactor made:

```diff
- .insert('textarea[name="bio"]', 'Born in a test case')
+ .insert(elT('bio'), 'Born in a test case')
```

```diff
<textarea name="bio"
+  data-test="bio"  
>
```

Still, I couldn't use the utility function `elT` inside wait() callbacks.
```js
// raw way
.wait(() => !document.querySelector('[data-test="signSubmit"]').disabled)

// with elT()
.wait(() => !document.querySelector(elT('signSubmit')).disabled)
```
> `Error: the string "elT is not defined" was thrown, throw an Error :)`
> `at <anonymous>`

Why does that happen? 🤔 

---

Closes #362.

### CODE REVIEW

**Comment by taoeffect** [comment]
@sandrina-p this now has merge conflicts

**Comment by hubudibu** [comment]
@sandrina-p indeed we have a scope problem there: as the doc about `wait(fn)` says 'Waits until the fn evaluated _on the page_', so not in our context but in the test browser's. fortunately, you can pass a second parameter for `wait`, that gets passed on to the function, you can see how at `.evaluate`'s description: https://github.com/segmentio/nightmare#evaluatefn-arg1-arg2 

so this works for me:
```
.wait((selector) => {
          return !document.querySelector(selector).disabled
        }, elT('signSubmit'))
```
for some reason it seems to not like passing functions this way, so I couldn't just pass `elT` and call it inside :( but passing the assembled selector works, although it's not super nice.

**Comment by sandrina-p** [comment]
@hubudibu so with your finding I've updated the tests. Even if it's not the nicest way of doing it, the most important part is `data-test` isn't repeated even once, so I think that's cool!

```js
        .wait(
          (el) => document.querySelectorAll(el).length < 1,
          elT('member')
        )
```

**Comment by taoeffect** [comment]
I did a quick scan, looks good to me, I think? @hubudibu do you agree, is this ready to merge?

**Comment by hubudibu** [comment]
👍 looks good to me! merging! 🎉 
just a sidenote: it would be easier to review the latest changes since the last review if you didn't squash the commits, so I would encourage doing every change in a separate commit the next time!

**Pull request merged**
