### PR TITLE
Fix the double Login-Modal redirection bug upon refresh

### LINKED ISSUE #702: Weird double-LoginModal redirection upon refresh
### Problem

When a browser tab is open and logged in and pointed at the dashboard, if the server (`grunt dev`) is quit (via `control-C`), and then re-run, and the tab is refreshed after the server is restarted (`grunt dev`, again), then the tab will be redirected to: http://localhost:8000/app/?modal=LoginModal&subcontent=LoginModal

### Solution

It should only have one modal (without `subcontent`) in the URL. Not sure if it should also redirect via `next=` to whatever the path was...

EDIT: also, visiting this URL results in the double-login modal, but I can't dismiss the final one.

Loading http://localhost:8000/app/?next=%2Fpay-group&modal=LoginModal (redirects to =>) http://localhost:8000/app/?next=%2Fpay-group&modal=LoginModal&subcontent=LoginModal (and can't dismiss second login modal), resulting in these errors in the console:

```
Object { _name: "NavigationDuplicated", name: "NavigationDuplicated", message: "Navigating to current location (\"/?next=%2Fpay-group&modal=LoginModal&subcontent=LoginModal\") is not allowed", stack: "", … }

websocket connection opened! backend.js:36:18
[sbp] okTurtles.events/emit 
Array [ "close-modal" ]
main.js:43:14
Object { _name: "NavigationDuplicated", name: "NavigationDuplicated", message: "Navigating to current location (\"/?next=%2Fpay-group&modal=LoginModal&subcontent=LoginModal\") is not allowed", stack: "", … }
```

### PR DESCRIPTION
**Pull request by SebinSong**
closes #702 

* Reason for the bug
the `next` query string added by the `loginGuard` [ [here ](https://github.com/okTurtles/group-income-simple/blob/master/frontend/views/components/Modal/Modal.vue#L27)] triggers the modal to open in `Home.vue` [ [here ](https://github.com/okTurtles/group-income-simple/blob/master/frontend/views/pages/Home.vue#L82)]
before the modal initialization procedure happens [here](https://github.com/okTurtles/group-income-simple/blob/master/frontend/views/components/Modal/Modal.vue#L27) in `Modal.vue`.
That apparently causes a weird (sort of a) chain reaction of calling `openModal()` method.

* A possible solution I suggest on this PR
move the **"if the query string has next specified then open Login Modal" ** logic from `Home.vue` into the initialization function in `Modal.vue`.

Hope this solution makes sense to you guys, @pieer and @taoeffect .

### CODE REVIEW

**Review by sandrina-p — DISMISSED** [review]

**Comment by SebinSong** [comment]
Cypress test passes locally, FYI

**Review by pieer — APPROVED** [review]

**Comment by pieer** [comment]
Excellent work @SebinSong

**Review by taoeffect — APPROVED** [review]
Excellent.

**Comment by taoeffect** [comment]
**NOTE: this is an exceptional merge that violates Rule 4 of our contributions guidelines because it's during a hackathon and I have approval to merge it, and others cannot merge it themselves because the build is failing, but it's an error unrelated to this PR.**

**Pull request merged**
