### PR TITLE
Make notification after identity contract is fully synced

### LINKED ISSUE #1837: Username should be displayed instead of contractID
### Problem

**Steps to reproduce**
- [Tab1] `u1` signs up, and creates a group
- [Tab2] `u2` joins the group
- [Tab3] `u1` logs in, and check the notification
- [Tab3] contractID is used instead of username in the notification (Attached screenshot)
image

**What should be happening**
- [Tab3] Username should be used instead of contractID

### Solution

Fix it

### PR DESCRIPTION
**Pull request by Silver-IT**
### Summary of Changes

- Closes #1837

### CODE REVIEW

**Review by Silver-IT — COMMENTED** [review]
Review ready!

**Review by taoeffect — CHANGES_REQUESTED** [review]
When I did Step 3:

> [Tab3] u1 logs in, and check the notification

I still see this error:

Screenshot 2024-02-14 at 7 25 36 PM

**Comment by Silver-IT** [comment]
> I still see this error:

This error is not described in the issue #1837. This issue should be added to the Issue #1839. Actually I found more errors in joining and leaving group, and I am currently working on those issues in [this branch](https://github.com/okTurtles/group-income/tree/1839-fix-errors-while-leaving-group).

**Comment by taoeffect** [comment]
> This error is not described in the issue https://github.com/okTurtles/group-income/issues/1837.

Well, I did mention it here: https://github.com/okTurtles/group-income/issues/1837#issuecomment-1934648958

However, if you'd like to fix it in a separate PR as part of fixing #1839, we can do that too.

It's late, so I'll return to this PR tomorrow, but in the meantime if you can please fix the merge conflict 🙏

**Review by taoeffect — DISMISSED** [review]
Approved! Great work on this @Silver-IT! 👏

**Review by taoeffect — APPROVED** [review]

**Pull request merged**
