### PR TITLE
fixed tooltip position on mobile

### PR DESCRIPTION
**Pull request by Vayras**
issue: #2434 

fixed the tooltip position on mobile 
Screenshot 2024-11-27 at 11 52 08 AM

### CODE REVIEW

**Review by taoeffect — CHANGES_REQUESTED** [review]
Awesome - thanks for your first PR @Vayras!

I found a bug - please be sure to thoroughly test all PRs and check the console for errors, in this case there's an issue with `bottom-center` not being a valid `Tooltip` direction:

Screenshot 2024-11-27 at 12 37 28 PM

I recommend also testing with dummy data, you can temporarily modify `GroupMembersActivity.vue` to use dummy data to test the display.

**Comment by Vayras** [comment]
@taoeffect thanks for the review I will fix this 🚀

**Comment by Vayras** [comment]
@taoeffect I have fixed the direction property can you please review this again for me? Thanks

**Review by taoeffect — CHANGES_REQUESTED** [review]
This change has the same problem.

**Comment by corrideat** [comment]
@Vayras If you take a look at `Tooltip.vue`, these are the allowed attributes:

```js
    direction: {
      type: String,
      validator: (value) => ['bottom', 'bottom-left', 'bottom-right', 'right', 'left', 'top', 'top-left'].includes(value),
      default: 'bottom'
    },
```

If you need other values, you need to modify `Tooltip.vue`. However, your PR 'works' because the default value of `bottom` will actually be centred at the bottom.

**Comment by Vayras** [comment]
@corrideat thanks for the info I looked at the file and found an attribute "bottom-middle" which is as you said the default attribute as well so I'm using that
Screenshot 2024-12-02 at 12 07 43 AM

**Comment by taoeffect** [comment]
@Vayras What file are you seeing that in? I don't see that in any file in the project.

**Comment by Vayras** [comment]
@corrideat Thanks for the heads up I think I was referring to the wrong tooltip file, fixed that in the latest commit

**Review by taoeffect — APPROVED** [review]
Seems to work in my tests, great job @Vayras!

**Pull request merged**
