### PR TITLE
Add post-group-creation confetti animation

### PR DESCRIPTION
**Pull request by SebinSong**
- issue #555 
- create a post group creation welcome page(GroupWelcome.vue) and add a confetti animation on the background.

### CODE REVIEW

**Review by taoeffect — CHANGES_REQUESTED** [review]
Haha this is great! 😄 🥳 🎊 

I am not an expert on HML5 animation so I've asked for the help of @pieer and @sandrina-p in reviewing this. I especially would like to know if this is the most CPU-efficient way of doing this animation or not (because we want to be mindful of users on low-powered phones).

From what I can tell after briefly scanning the source, this seems to use CSS animations, which is great, because from what I've read those are the most efficient.

One definite change I would request however is for the animation to stop after a period of time. I.e. if you could just throw out an initial "ball of confetti" and let that disappear. Ideally the confetti (and CPU/GPU usage) will disappear entirely after 5 seconds.

**Review by pieer — DISMISSED** [review]

**Comment by SebinSong** [comment]
@taoeffect Thanks for reviewing and pointing out the importance of CPU efficiency. Making the confetti particles disappear after a period of time sounds like a great way for that.

One thing I would love to let you know here is, the animation is actually performed by [window.requestAnimationFrame()](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame) Javascript method (not CSS Animation).
As soon as 'Groupwelcome.vue' component shows, it runs window.requestAnimationFrame loop([here](https://github.com/okTurtles/group-income-simple/pull/597/files#diff-2c74a71241b458b6d16fa1dcbd41a21dR232)) which iterates through the array of confetti objects and updates their positions and transformation values at each frame. Since those updated values are sent down to the corresponding confetti component as "props", Vue detects them and reflects the update in the DOM.

One main reason behind using Javascript is to make use of Math.random() method. I thought the movement of each confetti object needs to be randomized to make them look realistic(rather than making them all behave uniformly) and to achieve that, I thought their values of transformation functions(translate, rotate and scale) needed to be determined using Math.random().

But like you said above, it appears that CSS animations are generally less resource-heavy than JS animation, according to a little experiment done in [here](https://www.youtube.com/watch?v=E72WV7EjWjE) by a developer. :)

P.S. I came across [this article](https://developer.mozilla.org/en-US/docs/Web/Performance/CSS_JavaScript_animation_performance#Performance_comparison_transitions_vs._requestAnimationFrame) while doing research on the CPU efficiency of animation and thought you might find it interesting as well, even though it doesn't seem to deal with CPU usage side of animation. :)

**Comment by taoeffect** [comment]
Thanks @SebinSong! That's super helpful. Also you've got a lot of positive feedback waiting for you in the chat :)

**Comment by SebinSong** [comment]
I appreciate all the positive feedback! :)

The updated animation works as below.
- 0.5 seconds after GroupWelcome.vue page is presented, the animation begins.
- The animation lasts about 5 seconds and then the confetti particles fade out.
- After all the particles disappear, the animation loop stops and the responsible svg tag is removed from the DOM.

**Review by taoeffect — APPROVED** [review]
Awesome! 😄  🎉

**Comment by SebinSong** [comment]
Thank you! :)

**Pull request merged**
