### PR TITLE
fix: remove link style animation

### LINKED ISSUE #642: Fix links style
### Problem

Aug-29-2019 12-25-23

The current link style is done with a custom border to simulate a "fancy underline". Because of its nature, the style breaks when the link has two lines.

### Solution

@mmbotelho I noticed that on Figma we use a default underline. Which behavior is the correct here?

cc @pieer @taoeffect

### PR DESCRIPTION
**Pull request by sandrina-p**
Closes #642

edit
hover message

### CODE REVIEW

**Review by mmbotelho — CHANGES_REQUESTED** [review]
There seems to be a weird thing going on, where some links don't have an underline:
Captura de ecrã 2019-09-18, às 19 23 00
Captura de ecrã 2019-09-18, às 19 24 06

Others:
Captura de ecrã 2019-09-18, às 19 25 06

**Comment by mmbotelho** [comment]
Found another one @sandrina-p:

Captura de ecrã 2019-09-18, às 19 28 59

BTW, I am looking at these on Google Chrome

**Comment by sandrina-p** [comment]
@mmbotelho all fixed!

Note:
- some links that didn't have border were `<button />` instead of `<a />` so it was a missing style, all scenarios should be fixed now.
- removing the border-bottom from links with icons was tricky... but I found a way and now we just need to add `.has-icon` to the `.link`. This is something that needs to be done in each case, this is, it isn't a  "global fix" to all the links with icons, so if you find any other link with icon let me know, so I can add the class.  This was added to the Design System as well (cc @pieer)
- regarding the message link, look closer 👀 (or debug it). Both `color` and `border-bottom-color` turn grey on hover/focus as expected 😆

**Comment by mmbotelho** [comment]
Thank you, everything looks great now 😄 

> regarding the message link, look closer 👀 (or debug it). Both color and border-bottom-color turn grey on hover/focus as expected

It doesn't @sandrina-p :
Captura de ecrã 2019-09-19, às 14 14 21

It's behaving weirdly

**Comment by mmbotelho** [comment]
The spacing in the `button` is not the same as in `a` links. The `a` links have the correct spacing. 

I think you need to add a 2px padding to the bottom of the `buttons` (or something like that)

Captura de ecrã 2019-09-19, às 14 19 46

cc @sandrina-p

**Comment by sandrina-p** [comment]
@mmbotelho button.link fixed, it was missing a correct `line-height`. Regarding the border color... it's a very weird bug from Chrome and I have no idea why... it works fine on both Safari and Firefox 🤔

**Review by mmbotelho — APPROVED** [review]

**Comment by mmbotelho** [comment]
> Regarding the border color... it's a very weird bug from Chrome and I have no idea why

No worries, it's not that important. We can keep it as it is. 

Thank you for doing these changes, it's perfect now 🎉

**Review by taoeffect — APPROVED** [review]
Looks good to me! Deferring to @pieer for final review.

**Review by pieer — APPROVED** [review]

**Comment by pieer** [comment]
We can merge now

**Pull request merged**
