### PR TITLE
#347 Update Sidebar + Navbar to match designs

### LINKED ISSUE #347: Update Dashboard design
### Problem

currently the prototype UI isn't very intuitive. the basis of all group operations, the dashboard, has a somewhat disorganized and unprofessional feel.

### Solution

Update dashboard design based on the new mockup @willstanley came up with as part of #327 , following the conversation captured below.

### Latest designs:

dashboard with notification - v2

progress bar hover state:

dashboard with notification - v2 - hover

### Comments so far, to give context to current design:

- groupIncome brand colors should be kept
- default widget setup should be kept:
	- basic group info: name, description, mincome
	- voting announcement area
	- customizable area: members, contributions, history, settings
- the *feel* should be inviting and friendly but also professional   
aka “kindergarten professional” theme

- The word "Contributions" changed to "Pledges", both to indicate that there is a time during the month when people have yet to distributing their pledged amount (indicated in the "progress bar"), and also because there are different kinds of contributions (non-monetary ones as well)
- The "Group Members" section in the dashboard will not show $0 for people who aren't contributing monetary value, instead there are different colored pill boxes underneath their profile picture that indicate the kind of value they're providing to the group. There will be various categories of value when the user signs up for a group, and so a user's "primary value" to the group can be monetary contributions (green pill box, with dollar amount), or it could be "housekeeping", or even something as nebulous as "cuteness" (perhaps it's a kid)
- let users pick what their primary category is, even if they contribute monetary value
- the "progress bar" shows the percentage of the monetary value pledged that you're responsible for (if you pledged any)

### Last comments, design todos:
-  make the category pills stand out less, by making the colors lighter or whatever, and only allowing one primary category to be shown
-  make the progress bar, and especially the display of the amount contributed so far, less "busy" by taking inspiration from the "Support History" boxes below (just making it horizontal instead of vertical)

### PR DESCRIPTION
**Pull request by sandrina-p**
Following and Closes #347 

I've updated Sidebar and Navbar layout to match the design on #347.
- Now the layout is fluid (100% window width), but the Dashboard itself has a max-width, so isn't too large.
- Sidebar `"is-active"` logic isn't working, so any tab is never active, but the design for the class is done. BTW, how can I debug easily a vue component? On react it's easy as `{ console.log('x')}` but on Vue I couldn't make it work, neither using breakpoints... What's the trick?
- I've noticed the designs don't have `Pay Group` link, so to not erase it, I've kept it on navbar until we figure out a better way.
- The "Create Group" link was added to homepage "Welcome to GroupIncome" when logged for the first time.

Some parts of the layout don't match exactly the design (typography sizes / colors). It only uses bulma classes for now. I believe we can still iterate a lot on the navigation (sidebar + navbar) and elements hierarchy, but let's keep that for another iteration when we have #387 merged. I prefer to have small but fast iterations, what do you think?

image

### CODE REVIEW

**Comment by taoeffect** [comment]
> Sidebar "is-active" logic isn't working, so any tab is never active, but the design for the class is done

Should this perhaps be fixed before merging?

> BTW, how can I debug easily a vue component? On react it's easy as { console.log('x')} but on Vue I couldn't make it work, neither using breakpoints... What's the trick?

Sorry, don't understand. What are you trying to do? We can do a video chat if you'd like, and/or ask @hubudibu for help.

>  but let's keep that for another iteration when we have #387 merged. I prefer to have small but fast iterations, what do you think?

Should I review and merge this PR before #387 or after #387?

**Comment by sandrina-p** [comment]
Both PR are independent, but if it this one goes after it gets cleaner.

**Comment by hubudibu** [comment]
I'm also not sure what you miss from debugging, but from the top of my head
- if you haven't already, install vue devtools https://chrome.google.com/webstore/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd?hl=en to inspect components and their data/methods
- you can console.log in the script part
- you can display any local variable (data, computed) in the template between {{ moustaches }}

the template does'nt get translated to JS like the JSX in react, so you can't write plain js in the template tags, that is true. maybe if you give an example on what you would console.log I could help more

**Review by taoeffect — CHANGES_REQUESTED** [review]
merge conflict needs fixing

**Comment by sandrina-p** [comment]
>> Sidebar "is-active" logic isn't working, so any tab is never active, but the design for the class is done
> Should this perhaps be fixed before merging?

Fixed @taoeffect 😊

**Pull request merged**
