### PR TITLE
Fix incorrect badge while switching group

### LINKED ISSUE #1835: Incorrect badge while switching group
### Problem

**Steps to reproduce**
- `u1` signs up, and creates a group `g1`
- `u2` joins the group `g1`
- `u2` creates a new group `g2`
- `u1` creates a direct message with `u2`, and says greetings
- `u2` switches group, and checks the badges in groups list in the left sidebar

### Solution

Fix it

### PR DESCRIPTION
**Pull request by Silver-IT**
### Summary of Changes

- Closes #1835

### CODE REVIEW

**Review by Silver-IT — COMMENTED** [review]
Ready for the review!

**Review by Silver-IT — COMMENTED** [review]
Reverted all changes regarding pinning contracts and removed manifest.json file too.
It's now ready for the review the only changes in this PR.

**Review by taoeffect — COMMENTED** [review]
This PR must be merged after #1854 (and fix the conflicts that will result)

**Review by taoeffect — APPROVED** [review]
Again @Silver-IT - great catch! You keep finding and fixing UI bugs we missed, excellent work! 😄 👏

**Pull request merged**
