### PR TITLE
Fix heisenbug while checking payment details

### LINKED ISSUE #2168: Heisenbug: group-paying.spec.js modal related bug
### Problem

Please see [this video](https://cloud.cypress.io/projects/q6whky/runs/2604/test-results/e07c7329-a1fe-480b-9f86-c6d17f5f6baa/video?actions=%5B%5D&browsers=%5B%5D&groups=%5B%5D&isFlaky=%5B%5D&modificationDateRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D&orderBy=EXECUTION_ORDER&oses=%5B%5D&specs=%5B%5D&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D&testingTypesEnum=%5B%5D&utm_source=github).

Screenshot 2024-07-08 at 12 51 39 PM

This is now happening periodically on `master`.

### Solution

It seems like the way one of the elements is being grabbed needs to be changed.

### LINKED ISSUE #2230: Duplicated notifications are possibly created in Cypress
### Problem

In [this Cypress test](https://cloud.cypress.io/projects/q6whky/runs/2743/test-results/5c8cbd1f-a8e6-489a-8b31-b6b7e8e379d8/video?actions=%5B%5D&browsers=%5B%5D&groups=%5B%5D&isFlaky=%5B%5D&modificationDateRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D&orderBy=EXECUTION_ORDER&oses=%5B%5D&specs=%5B%5D&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D&testingTypesEnum=%5B%5D&utm_source=github), we can see the two notifications are same.
image

Actually, it is not allowed to create duplicated notification and we do this by comparing its hash.
```
[keys.ADD_NOTIFICATION] (state, notification: Notification) {
  if (state.items.some(item => item.hash === notification.hash)) {
    // We cannot throw here, as this code might be called from within a contract side effect.
    return console.error('This notification is already in the store.')
  }
  state.items.push(notification)
  // Sort items in chronological order, newest items first.
  state.items.sort(compareOnTimestamp)
}
```
I guess the reason might be the duplicated notification is created before the Vuex module `notifications` is cloned from the IndexedDB after login.

### Solution

Fix it.

### PR DESCRIPTION
**Pull request by Silver-IT**
### Summary of Changes

- Closes #2168
- Closes #2230

### CODE REVIEW

**Review by Silver-IT — COMMENTED** [review]
Ready for the review!

**Review by taoeffect — CHANGES_REQUESTED** [review]
As far as I can tell, this PR is unlikely to close #2168 because it does not appear to touch any code related to that.

**Comment by Silver-IT** [comment]
> As far as I can tell, this PR is unlikely to close https://github.com/okTurtles/group-income/issues/2168 because it does not appear to touch any code related to that.

Actually, it does. The main reason is that the `NEW_DISTRIBUTION_PERIOD` notification is created just after the select element but before the click event is called. What I did is that make the Cypress to wait until all the notifications are created before select element and click it.

**Review by Silver-IT — COMMENTED** [review]
Ready for the review!

**Review by taoeffect — APPROVED** [review]
Alright, let's hope this does it! 🤞

**Pull request merged**
