### PR TITLE
#2325 - add `stringMax()` validator for user display name

### LINKED ISSUE #2325: Implement `stringMax` validation for user display name
### Problem

Apparently there is no `stringMax()` validation implemented for `displayName` field in identity contract. Also, it needs `n/max` indicator UI in `UserSettingModal.vue`, Just like how it is in the user bio input below.

### Solution
Implement them

### PR DESCRIPTION
**Pull request by SebinSong**
closes #2325

### CODE REVIEW

**Comment by corrideat** [comment]
Is this a good idea (or at least the 80 characters limit)? While I agree it's usually excessive, there are many cases where someone's full name can be pretty long (e.g., Pablo Picasso, Hubert Blaine Wolfeschlegelsteinhausenbergerdorff (yes, that's the 'short' version)).

Another example: Karl-Theodor zu Guttenberg (the current German politician).

However, whether someone would use their very long full name as a display name, I'm not sure.

**Comment by taoeffect** [comment]
> Karl-Theodor zu Guttenberg

That's 26 characters

> Pablo Picasso, Hubert Blaine Wolfeschlegelsteinhausenbergerdorff

64 characters.

So yeah... I think 80 is sufficient. 😄

**Comment by SebinSong** [comment]
@corrideat Its my perception that people with long name usually want to use a shorter version when possible and also often encourage others to do so too.(Who would enjoy typing 80 characters each time they call someone in the chat?)

**Comment by corrideat** [comment]
> Karl-Theodor zu Guttenberg

Karl-Theodor Maria Nikolaus Johann Jacob Philipp Franz Joseph Sylvester Buhl-Freiherr von und zu Guttenberg

> Pablo Picasso

Pablo Diego José Francisco de Paula Juan Nepomuceno Cipriano de la Santísima Trinidad Ruiz Picasso

> Hubert Blaine Wolfeschlegelsteinhausenbergerdorff

This one is over half a KiB

> Its my perception that people with long name usually want to use a shorter version when possible and also often encourage others to do so too

Probably that's what most prefer, yes. But since 80 characters aren't going to fit on screen / the UI component anyhow, it seems like an arbitrary limit.

**Review by taoeffect — APPROVED** [review]
LGTM!

**Pull request merged**
