### PR TITLE
Issue #1617 - [Bug] Revoke link menu item missing on anyone can join links

### LINKED ISSUE #1617: [Bug] Revoke link menu item missing on anyone can join links
### Problem

Screen Shot 2023-05-27 at 11 41 05 AM

On mobile the 3 dots do appear:

Screen Shot 2023-05-27 at 11 42 48 AM

We just need to make sure they appear on desktop too.

Interestingly, they do appear on desktop for links created by proposals:

Screen Shot 2023-05-27 at 11 46 15 AM

### Solution

For the anyone-can-join link, the 3 dots should always appear if the group creator is currently logged in, on both desktop and mobile.

They should be hidden on both desktop and mobile if it's someone else that is logged in.

### LINKED ISSUE #1626: [Bug] Need to actually increase width of chat view
### Problem

Something I missed in my review of PR #1625. (h/t @corrideat for catching this!)

Screen Shot 2023-06-01 at 12 37 21 PM

### Solution

Test thoroughly with very long words that are not broken, and also long sentences and make sure the full width is used.

### PR DESCRIPTION
**Pull request by SebinSong**
closes #1617 
closes #1626

### CODE REVIEW

**Review by taoeffect — CHANGES_REQUESTED** [review]
Nicely done @SebinSong, however one issue: for the anyone can join link, the dots should be hidden for everyone except the group creator per the issue Solution:

> For the anyone-can-join link, the 3 dots should always appear if the group creator is currently logged in, on both desktop and mobile.
> 
> They should be hidden on both desktop and mobile if it's someone else that is logged in.

**Comment by SebinSong** [comment]
@taoeffect 
This PR contains the work for resolving the issue #1626 too

**Review by taoeffect — CHANGES_REQUESTED** [review]
This seems to introduce a regression as the chat area does not stretch at all:

Screen Shot 2023-06-02 at 5 58 33 PM

Also while testing I found another bug and opened an issue: #1632

**Comment by SebinSong** [comment]
@taoeffect forgot to merge the latest `master` in to this feature branch. updated again.

**Review by taoeffect — APPROVED** [review]
Nice! Approved! Will merge as soon as tests pass 🙂

**Pull request merged**
