### PR TITLE
Close #822: Add background to app header on smaller screens

### LINKED ISSUE #822: Add background to app header on smaller screens
### Problem

The app header does not have a background and is showing up behind other components on the page:

Captura de ecrã 2020-02-04, às 19 57 28

### Solution
Make it behave like this:
Captura de ecrã 2020-02-04, às 20 02 29

Edit: 
I just noticed that the fullscreen modals also have this problem.  The header (title + subtitle (optional) + close button) should also be fixed, with a background color.

### PR DESCRIPTION
**Pull request by pieer**
I also fix sticky header position on mobile for modal

### CODE REVIEW

**Review by taoeffect — CHANGES_REQUESTED** [review]
Great job @pieer!

Noticed only one minor issue on the Group Settings page while scrolling.

The down arrow (v) for the dropdown of the default currency appears above the header bar when scrolling:

Screen Shot 2020-04-21 at 4 31 06 PM

**Comment by pieer** [comment]
This is fixed @taoeffect. Thanks

**Review by mmbotelho — APPROVED** [review]
Perfect @pieer ! Thank you 😄

**Review by taoeffect — APPROVED** [review]
👏

**Pull request merged**
