### PR TITLE
#1811 - Wrong file attachment detection in the chatroom

### LINKED ISSUE #1811: Wrong file attachment detection in the chatroom
### Problem
In a chatroom, when a random text string is selected and dragged over the chatroom message UI, it's perceived as a file attachment and below overlay screen is triggered. This is wrong and should be corrected.

https://github.com/okTurtles/group-income/assets/17641213/0f99fe2d-381e-484e-9022-9ef1449c6c6f

### Solution
Fix it.

### PR DESCRIPTION
**Pull request by SebinSong**
closes #1811

### CODE REVIEW

**Review by taoeffect — CHANGES_REQUESTED** [review]
Hmm, I'm not sure what changed... but dragging text shouldn't bring up the file attachment overlay at all:

https://github.com/okTurtles/group-income/assets/138706/b7f0c04b-4101-4147-ad63-a6b61be66161

**Comment by SebinSong** [comment]
@taoeffect 
Did you test in this feature branch of mine - `sebin/task/#1811-file-attachment-bug-in-chat`?
The same action doesn't lead to displaying the overlay UI for me.

https://github.com/okTurtles/group-income/assets/17641213/1299de84-43a9-4356-98b2-a11440343534

**Comment by taoeffect** [comment]
@SebinSong odd... I thought I did. I tried it again just now and it seems to be fixed. However now I'm having the opposite problem: I can't drag anything onto the chat view. Dragging an image from the Finder onto the chat view doesn't bring up the overlay and dropping the file doesn't attach anything. (Tested in FFDev)

**Comment by SebinSong** [comment]
@taoeffect updated the PR with the fix for that error!

**Review by taoeffect — APPROVED** [review]
Works! 😄

**Pull request merged**
