### PR TITLE
Do some cleanup to the create group view.

### PR DESCRIPTION
**Pull request by danawoodman**
- Move a view specific style into component scoped styles
- Format input HTML so it is more legible
- Use `const` instead of `let` where possible
- Use new function syntax for object
- Remove irrelevant comment

### CODE REVIEW

**Comment by danawoodman** [comment]
@taoeffect any issues with this change? Would be good to merge soon as I'm making changes in this file and want to avoid conflicts if possible.

**Comment by taoeffect** [comment]
OK, as suspected, after merging Mailbox2, there are conflicts that need to be fixed first. /cc @danawoodman

**Comment by danawoodman** [comment]
@taoeffect ok ill resolve these

**Comment by danawoodman** [comment]
@taoeffect ok PR has been updated to resolve conflicts 👍

**Comment by danawoodman** [comment]
@taoeffect think this should be good to merge?

**Pull request merged**
