### PR TITLE
Implement distribution locked warning tooltip

### LINKED ISSUE #1914: Implement "distribution locked" warning & tooltip
### Problem

The "distribution locked" warning & tooltip has been wonderfully designed by @leihla and is ready for implementation.
image

As noted on Figma, this should appear once the first payment for the period is made, which locks the distribution. 

When the distribution is locked, that should trigger a notification with the same text as the tooltip: "First payment sent. Distribution is now locked."

### Solution

Send a PR with implemented warning & tooltip and notification.

Figma: https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?type=design&node-id=23123-223870&mode=design

### PR DESCRIPTION
**Pull request by Silver-IT**
### Summary of Changes

- Closes #1914

### CODE REVIEW

**Review by Silver-IT — COMMENTED** [review]
Ready for the review!

**Review by taoeffect — CHANGES_REQUESTED** [review]
Nice, it seems to work well @Silver-IT!

Two issues discovered on mobile:

### Poor positioning

Screenshot 2024-04-12 at 12 41 12 PM

I've gone ahead and [updated Figma](https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?type=design&node-id=26959%3A28250&mode=design&t=iTiqXNNESC4N1wsq-1) for the mobile design with how it should be positioned.

Screenshot 2024-04-12 at 12 43 22 PM

### Tooltip hidden

Make sure to test mobile and verify that the tooltip is readable. Perhaps even have it displayed above instead of below, as currently it gets cut off:

Screenshot 2024-04-12 at 12 42 01 PM

**Review by taoeffect — CHANGES_REQUESTED** [review]
Spacing between message and button is too small, needs to be pixel-perfect with designs:

Screenshot 2024-04-12 at 11 18 22 PM

**Review by taoeffect — CHANGES_REQUESTED** [review]
Screenshot 2024-04-13 at 4 30 38 PM

I see no difference.

**Review by taoeffect — APPROVED** [review]
Great job @Silver-IT !

**Pull request merged**
