### PR TITLE
Fix Cypress heisenbug in group-chat

### LINKED ISSUE #2256: Heisenbug in `group-chat.spec.js`
### Problem

https://github.com/user-attachments/assets/772eebd1-dacc-44e3-95ee-8a99ed0f2a48

- Example [failed build](https://github.com/okTurtles/group-income/actions/runs/10101571423/job/27935432333?pr=2255)
- Example [Cypress Dasboard issue](https://cloud.cypress.io/projects/q6whky/runs/2803/specs?utm_source=github)

Test failure info:

```
    1) user3 joins the Dreamers group and general channel again and logout

  15 passing (2m)
  1 pending
  1 failing

  1) Group Chat Basic Features (Create & Join & Leave & Close)
       user3 joins the Dreamers group and general channel again and logout:
     AssertionError: Timed out retrying after 30000ms: expected '<span.c-twrapper>' to contain 'user3-14328999999997904524207'
      at Context.eval (http://127.0.0.1:8000/__cypress/tests?p=test/cypress/support/index.js:2073:65)
  Console Logs:
```

### Solution

Uncomment that out and push a PR to verify the tests are still failing because of that line.

Figure out the problem and fix.

### PR DESCRIPTION
**Pull request by Silver-IT**
### Summary of Changes

- Closes #2256

### CODE REVIEW

**Review by taoeffect — CHANGES_REQUESTED** [review]
This doesn't fix the heisenbug: https://github.com/okTurtles/group-income/actions/runs/10123374805/job/28000307999

Screenshot 2024-07-27 at 10 46 15 AM

**Comment by Silver-IT** [comment]
> This doesn't fix the heisenbug: https://github.com/okTurtles/group-income/actions/runs/10123374805/job/28000307999

Sorry, I will check it again. However, I can not see the error message.
image

**Comment by Silver-IT** [comment]
While I was running the following command to get the Cypress failed on my local, I could encounter the Cypress failure.
```
while npx cypress run -c 'baseUrl=http://localhost:8000' --spec "test/cypress/integration/group-chat.spec.js"; do :; done
```

https://github.com/user-attachments/assets/ed440efa-1519-4a7c-958b-9df5c24f732e

Not sure but I think it seems to be related to the Issue #2171.

**Comment by taoeffect** [comment]
Closing in favor of #2294 which claims to fix this as well

**Pull request closed without merging**
